const ladoCuadrado = 5;
console.log("Los lados del cuadrado miden: " + ladoCuadrado + " cm");

const perimetroCuadrado = ladoCuadrado * 4;
console.log("El perimetro del cuadrado es: " + perimetroCuadrado + " cm");

const areaCuadrado = ladoCuadrado * ladoCuadrado;
console.log("El area del cuadrado es: " + areaCuadrado + " cm^2");

//Triangulo

const ladoTriangulo1 = 6;
const ladoTriangulo2 = 6;
const base = 6;
console.log("Los lados del cuadrado miden: " + ladoCuadrado + " cm");
